spring:
  application:
    name: url-shortener-backend

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expiration: 172800000

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      sanish:
        url: DEBUG

client:
  url: ${CLIENT_URL}
